a1=read.table("/Users/anirudhgambhir/Documents/COLLEGE/SEM5/R Prog./Datasets/Coursera Datasets/household_power_consumption.txt",na.strings = "?",header = T,sep = ';')
a1$Date=as.Date(a1$Date,format = "%d/%m/%Y")
a1=subset(a1,a1$Date=="2007-02-01"|a1$Date=="2007-02-02")
a1$Date=as.POSIXlt(a1$Date,format = "%H:%M:%S")
datetime <- strptime(paste(a1$Date, a1$Time,sep = ' '), "%Y-%m-%d %H:%M:%S")
plot(datetime, a1$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(datetime, a1$Sub_metering_2, type="l", col="red")
lines(datetime, a1$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2, col=c("black", "red", "blue"))
dev.copy(png,"plot3.png", width=480, height=480)
dev.off()
